name: Go
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: auto
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Go get
        run: |
          go get -u github.com/golang/mock
          go get -u github.com/golang/mock/mockgen
          go get -u github.com/stretchr/testify

      - name: Generate mocks files
        run: go generate ./...

      - name: Test
        run: go test -v ./...
